// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Quiz_platform_User.DAL.Models;

[Index("QuestionId", Name = "IX_Answers_QuestionId")]
public partial class Answer
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string OptionText { get; set; }

    public bool IsCorrect { get; set; }

    public int QuestionId { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Answers")]
    public virtual Question Question { get; set; }
}