// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Quiz_platform_User.DAL.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Quiz_platform_User.DAL.Models
{
    public partial interface IQuizSystemContextProcedures
    {
        Task<List<GetAllQuizesResult>> GetAllQuizesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
