// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Quiz_platform_User.DAL.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Quiz_platform_User.DAL.Models
{
    public partial class QuizSystemContext
    {
        private IQuizSystemContextProcedures _procedures;

        public virtual IQuizSystemContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new QuizSystemContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IQuizSystemContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class QuizSystemContextProcedures : IQuizSystemContextProcedures
    {
        private readonly QuizSystemContext _context;

        public QuizSystemContextProcedures(QuizSystemContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetAllQuizesResult>> GetAllQuizesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetAllQuizesResult>("EXEC @returnValue = [dbo].[GetAllQuizes]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
